image: asciidoctor/docker-asciidoctor

ebooks:
  stage: build
  script:
    - asciidoctor WaRP.adoc
    - asciidoctor-pdf WaRP.adoc
    - asciidoctor-epub3 WaRP.adoc
  artifacts:
    paths:
      - WaRP.html
      - WaRP.pdf
      - WaRP.epub

test_epub:
  stage: test
  script:
    - asciidoctor-epub3 -a ebook-validate WaRP.adoc
