image: asciidoctor/docker-asciidoctor

ebooks:
  stage: build
  script:
    - asciidoctor WaRP.adoc
    - asciidoctor-pdf WaRP.adoc
    - asciidoctor-epub3 WaRP.adoc
    - asciidoctor-epub3 -a ebook-format=kf8 WaRP.adoc
  artifacts:
    paths:
      - WaRP.html
      - WaRP.pdf
      - WaRP.mobi
      - WaRP.epub

# I haven't seen a way to validate non-epub results
test_epub:
  stage: test
  script:
    - asciidoctor-epub3 -D output -a ebook-validate WaRP.adoc
