image: asciidoctor/docker-asciidoctor

# Direct epub generation disabled until I adhere to the rules in the asciidoctor-epub3 docs:
# https://github.com/asciidoctor/asciidoctor-epub3#structuring-your-manuscript

html:
  stage: build
  script:
    - asciidoctor WaRP.adoc
    - asciidoctor-pdf WaRP.adoc
    #- asciidoctor-epub3 WaRP.adoc
  artifacts:
    paths:
      - WaRP.html
      - WaRP.pdf
      #- WaRP.epub

#test_epub:
#  stage: test
#  script:
#    - asciidoctor-epub3 -D output -a ebook-validate WaRP.adoc

ebook:
  stage: build
  before_script:
    - apt-get update -qq ; apt-get install -y -qq calibre
  dependencies:
    - html
  script:
    - ebook-convert WaRP.html WaRP.epub
    - ebook-convert WaRP.html WaRP.mobi
  artifacts:
    paths:
      - WaRP.epub
      - WaRP.mobi
