image: asciidoctor/docker-asciidoctor

stages:
  - build
  - test

html:
  stage: build
  script:
    - asciidoctor WaRP.adoc
  artifacts:
    paths:
      - WaRP.html

pdf:
  stage: build
  script:
    - asciidoctor-pdf WaRP.adoc
  artifacts:
    paths:
      - WaRP.pdf

epub:
  stage: build1
  script:
    - asciidoctor-epub3 WaRP.adoc
  artifacts:
    paths:
      - WaRP.epub

mobi:
  stage: build
  script:
    - asciidoctor-epub3 -a ebook-format=kf8 WaRP.adoc
  artifacts:
    paths:
      - WaRP.mobi

# I haven't seen a way to validate non-epub results
test_epub:
  stage: test
  script:
    - asciidoctor-epub3 -D output -a ebook-validate WaRP.adoc
